#!/usr/bin/env python3
"""Generate src/isar_tools/source/afp_commands.py from an AFP checkout.

For every AFP session: the commands (beyond the built-in table) that a theory
importing one of its theories can see, read from the theory headers' `keywords`
declarations along the imports, the way `isar` computes them with `-d $AFP`.
Sessions that add nothing are left out; equal command sets are stored once.

    python scripts/gen_afp_commands.py ~/afp/thys [--out FILE]
"""

import json
import subprocess
import sys
from pathlib import Path

from isar_tools.project.model import Project
from isar_tools.source import afp_commands
from isar_tools.source.keywords import BUILTIN_COMMANDS

OUT = Path(__file__).resolve().parent.parent / "src" / "isar_tools" / "source" / "afp_commands.py"


def version(afp: Path) -> str:
    run = subprocess.run(
        ["git", "-C", str(afp), "log", "-1", "--format=%h %cs"],
        capture_output=True,
        text=True,
        check=False,
    )
    return run.stdout.strip() or "unknown revision"


def main() -> int:
    args = sys.argv[1:]
    out = OUT
    if len(args) == 3 and args[1] == "--out":
        out = Path(args[2])
        args = args[:1]
    if len(args) != 1 or not (Path(args[0]) / "ROOTS").is_file():
        print(
            "usage: gen_afp_commands.py AFP_THYS_DIRECTORY [--out FILE] (with a ROOTS file)",
            file=sys.stderr,
        )
        return 2
    afp = Path(args[0]).resolve()
    # Read the AFP as it is, not through the table being regenerated.
    afp_commands.SESSIONS.clear()
    project = Project.load(afp)
    tables: list[tuple[tuple[str, str], ...]] = []
    sessions: dict[str, int] = {}
    for session in sorted(project.own_sessions, key=lambda s: s.name):
        visible: dict[str, str] = {}
        for path in project.owned_theories(session).values():
            for name, kind in project.keywords_for(path).items():
                if BUILTIN_COMMANDS.get(name) != kind:
                    visible[name] = kind.value
        if not visible:
            continue
        table = tuple(sorted(visible.items()))
        if table not in tables:
            tables.append(table)
        sessions[session.name] = tables.index(table)

    lines = [
        '"""Commands that AFP sessions make visible to the theories importing them.',
        "",
        f"Generated by scripts/gen_afp_commands.py from the AFP at {version(afp)};",
        "do not edit. Used for imports from sessions that are not on the session",
        "path, so AFP commands are recognised without an AFP checkout.",
        '"""',
        "",
        "# Distinct command sets: (command, kind) pairs.",
        "TABLES: tuple[tuple[tuple[str, str], ...], ...] = (",
    ]
    for table in tables:
        pairs = [f"({json.dumps(name)}, {json.dumps(kind)})" for name, kind in table]
        if len(pairs) == 1:  # as ruff formats a one-element tuple
            lines.append(f"    ({pairs[0]},),")
        else:
            lines += ["    (", *(f"        {pair}," for pair in pairs), "    ),"]
    lines += [")", "", "# Session name -> index into TABLES.", "SESSIONS: dict[str, int] = {"]
    lines += [f"    {json.dumps(name)}: {index}," for name, index in sessions.items()]
    lines += ["}", ""]
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out}: {len(sessions)} sessions, {len(tables)} command sets", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
